<script setup lang="ts">
import { computed,ref } from 'vue';import {useQuery,useQueryClient}from '@tanstack/vue-query';import{api}from '@/api/client';import CoachingOperationsView from '@/views/CoachingOperationsView.vue'
type Coach={id:number;name:string;hourly_rate:number;email?:string};type Session={id:number;coach_profile_id:number;starts_at:string;ends_at:string;status:string;amount:number};const c=useQueryClient();const name=ref('');const rate=ref<number|undefined>();const email=ref('');const coachId=ref<number>();const starts=ref('');const ends=ref('');const msg=ref('');const err=ref('');const busy=ref(false);const coaches=useQuery({queryKey:['coaches'],queryFn:async()=>{const r=await api.get('/coaches');return r.data.data??[]}});const sessions=useQuery({queryKey:['coaching-sessions'],queryFn:async()=>{const r=await api.get('/coaching-sessions');return r.data.data??[]}});const coachList=computed<Coach[]>(()=>coaches.data.value??[]);const sessionList=computed<Session[]>(()=>sessions.data.value??[]);async function refresh(){await Promise.all([c.invalidateQueries({queryKey:['coaches']}),c.invalidateQueries({queryKey:['coaching-sessions']})])}async function addCoach(){if(!name.value||rate.value===undefined){err.value='Coach name and hourly rate are required.';return}busy.value=true;try{await api.post('/coaches',{name:name.value,email:email.value||undefined,hourly_rate:rate.value});msg.value='Coach created.';name.value='';await refresh()}catch(e:any){err.value=e.response?.data?.message??'Coach could not be created.'}finally{busy.value=false}}async function createSession(){if(!coachId.value||!starts.value||!ends.value){err.value='Select a coach and session times.';return}busy.value=true;try{await api.post('/coaching-sessions',{coach_profile_id:coachId.value,starts_at:starts.value,ends_at:ends.value});msg.value='Coaching session scheduled.';await refresh()}catch(e:any){err.value=e.response?.data?.message??'Session could not be scheduled.'}finally{busy.value=false}}async function action(s:Session,a:'complete'|'cancel'){busy.value=true;try{await api.post(`/coaching-sessions/${s.id}/${a}`);msg.value=`Session ${a}led.`;await refresh()}catch(e:any){err.value=e.response?.data?.message??'Action failed.'}finally{busy.value=false}}</script>
<template>
  <header class="page-header"><div><p class="eyebrow">COACHING</p><h1>Coaching</h1><p class="muted">Manage coaches and session schedules.</p></div></header>
  <p v-if="msg" class="action-message success">{{msg}}</p><p v-if="err" class="action-message error">{{err}}</p>
  <section class="membership-top-grid"><article class="panel membership-form"><h2>Add coach</h2><form @submit.prevent="addCoach"><label>Name<input v-model="name"/></label><label>Email<input v-model="email" type="email"/></label><label>Hourly rate<input v-model.number="rate" type="number" min="0"/></label><button class="secondary-button" :disabled="busy">Add coach</button></form></article><article class="panel membership-form"><h2>Schedule session</h2><form @submit.prevent="createSession"><label>Coach<select v-model.number="coachId"><option :value="undefined">Select coach</option><option v-for="coach in coachList" :key="coach.id" :value="coach.id">{{coach.name}}</option></select></label><label>Starts<input v-model="starts" type="datetime-local"/></label><label>Ends<input v-model="ends" type="datetime-local"/></label><button class="primary-button" :disabled="busy">Schedule</button></form></article></section>
  <section class="panel memberships-table"><h2>Coaching sessions</h2><div class="table-wrap"><table><thead><tr><th>Coach</th><th>Schedule</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="s in sessionList" :key="s.id"><td>{{coachList.find(x=>x.id===s.coach_profile_id)?.name??`Coach #${s.coach_profile_id}`}}</td><td>{{s.starts_at}} – {{s.ends_at}}</td><td>₱{{s.amount}}</td><td><span :class="['status-pill',s.status]">{{s.status}}</span></td><td><button v-if="s.status==='scheduled'" class="table-button confirm" @click="action(s,'complete')">Complete</button> <button v-if="s.status==='scheduled'" class="table-button cancel" @click="action(s,'cancel')">Cancel</button></td></tr></tbody></table></div></section>
  <CoachingOperationsView />
</template>
