<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { api, type ApiList } from '@/api/client'
type Org={id:number;name:string};type Facility={id:number;organization_id:number;name:string;address?:string;registration_open?:boolean};type Branch={id:number;name:string};type Court={id:number;name:string;sport?:string;status:string;base_price:number}
const client=useQueryClient();const orgName=ref('');const facilityName=ref('');const branchName=ref('');const courtName=ref('');const price=ref<number>();const orgId=ref<number>();const facilityId=ref<number>();const branchId=ref<number>();const message=ref('');const error=ref('')
const orgs=useQuery({queryKey:['organizations'],queryFn:async()=>((await api.get<ApiList<Org>>('/organizations')).data.data)});const facilities=useQuery({queryKey:['facilities'],queryFn:async()=>((await api.get<ApiList<Facility>>('/facilities')).data.data)});const branches=useQuery({queryKey:['facility-branches',facilityId],enabled:computed(()=>!!facilityId.value),queryFn:async()=>((await api.get<ApiList<Branch>>(`/facilities/${facilityId.value}/branches`)).data.data)});const courts=useQuery({queryKey:['branch-courts',branchId],enabled:computed(()=>!!branchId.value),queryFn:async()=>((await api.get<ApiList<Court>>(`/branches/${branchId.value}/courts`)).data.data)});const orgList=computed<Org[]>(()=>orgs.data.value??[]);const facilityList=computed<Facility[]>(()=>facilities.data.value??[]);const branchList=computed<Branch[]>(()=>branches.data.value??[]);const courtList=computed<Court[]>(()=>courts.data.value??[])
async function refresh(){await Promise.all(['organizations','facilities','facility-branches','branch-courts'].map(k=>client.invalidateQueries({queryKey:[k]})))} async function create(path:string,body:any,success:string){message.value='';error.value='';try{const r=await api.post(path,body);message.value=success;await refresh();return(r.data.data??r.data).id}catch(e:any){error.value=e.response?.data?.message??'Could not save changes.'}}
async function manage(path:string,item:{id:number;name:string},remove=false){if(remove&&!confirm(`Delete ${item.name}?`))return;try{if(remove)await api.delete(`${path}/${item.id}`);else{const name=prompt('Name',item.name);if(!name)return;const update=path==='/branches'||path==='/courts'?api.put:api.patch;await update(`${path}/${item.id}`,{name})}message.value=`${item.name} ${remove?'deleted':'updated'}.`;await refresh()}catch(e:any){error.value=e.response?.data?.message??'Could not update item.'}}
async function playerSignup(f:Facility){try{await api.patch(`/facilities/${f.id}/registration`,{registration_open:!f.registration_open});message.value=`Player self-registration ${f.registration_open?'closed':'opened'} for ${f.name}.`;await refresh()}catch(e:any){error.value=e.response?.data?.message??'Could not update player registration.'}}
</script>
<template><header class="page-header"><div><p class="eyebrow">FACILITIES</p><h1>Facility management</h1><p class="muted">Create and manage your organization, facilities, branches, and courts.</p></div></header><p v-if="message" class="action-message success">{{message}}</p><p v-if="error" class="action-message error">{{error}}</p><section class="setup-grid"><article class="panel setup-step"><h2>Organization</h2><form @submit.prevent="create('/organizations',{name:orgName},'Organization created.')"><input v-model="orgName" placeholder="Organization name"/><button class="secondary-button">Add</button></form><div class="selection-list"><button v-for="o in orgList" :key="o.id" :class="{selected:orgId===o.id}" @click="orgId=o.id"><strong>{{o.name}}</strong><span><a @click.stop="manage('/organizations',o)">Edit</a> · <a @click.stop="manage('/organizations',o,true)">Delete</a></span></button></div></article><article class="panel setup-step"><h2>Facility</h2><form @submit.prevent="create('/facilities',{organization_id:orgId,name:facilityName,timezone:'Asia/Manila'},'Facility created.')"><input v-model="facilityName" :disabled="!orgId" placeholder="Facility name"/><button class="secondary-button">Add</button></form><div class="selection-list"><button v-for="f in facilityList" :key="f.id" :class="{selected:facilityId===f.id}" @click="facilityId=f.id;branchId=undefined"><strong>{{f.name}}</strong><span><a @click.stop="manage('/facilities',f)">Edit</a> · <a @click.stop="manage('/facilities',f,true)">Delete</a> · <a @click.stop="playerSignup(f)">{{f.registration_open?'Close player signup':'Open player signup'}}</a></span></button></div></article><article class="panel setup-step"><h2>Branch</h2><form @submit.prevent="create(`/facilities/${facilityId}/branches`,{name:branchName,timezone:'Asia/Manila'},'Branch created.')"><input v-model="branchName" :disabled="!facilityId" placeholder="Branch name"/><button class="secondary-button">Add</button></form><div class="selection-list"><button v-for="b in branchList" :key="b.id" :class="{selected:branchId===b.id}" @click="branchId=b.id"><strong>{{b.name}}</strong><span><a @click.stop="manage('/branches',b)">Edit</a> · <a @click.stop="manage('/branches',b,true)">Delete</a></span></button></div></article><article class="panel setup-step"><h2>Court</h2><form @submit.prevent="create(`/branches/${branchId}/courts`,{name:courtName,base_price:price,status:'active'},'Court created.')"><input v-model="courtName" :disabled="!branchId" placeholder="Court name"/><input v-model.number="price" :disabled="!branchId" type="number" min="0" placeholder="Hourly price"/><button class="primary-button">Add court</button></form><div class="selection-list"><button v-for="c in courtList" :key="c.id"><strong>{{c.name}} · ₱{{c.base_price}}</strong><span><a @click.stop="manage('/courts',c)">Edit</a> · <a @click.stop="manage('/courts',c,true)">Delete</a></span></button></div></article></section></template>
