<script setup lang="ts">
import { computed, ref } from 'vue'; import { useQuery,useQueryClient } from '@tanstack/vue-query'; import { api } from '@/api/client'; import PaymentOperationsView from '@/views/PaymentOperationsView.vue'
type Membership={id:number;membership_plan_id:number;status:string};type Payment={id:number;reference:string;membership_id?:number;amount:number;method:string;provider?:string;status:string};type Provider={name:'paymongo'|'xendit';configured:boolean;mock?:boolean}
const client=useQueryClient();const membershipId=ref<number>();const method=ref('gcash');const provider=ref<'paymongo'|'xendit'>('paymongo');const refundAmount=ref<number|undefined>();const message=ref('');const error=ref('');const busy=ref(false)
const memberships=useQuery({queryKey:['memberships'],queryFn:async()=>{const r=await api.get('/memberships');return r.data.data??[]}});const payments=useQuery({queryKey:['payments'],queryFn:async()=>{const r=await api.get('/payments');return r.data.data?.data??r.data.data??[]}});const providers=useQuery({queryKey:['payment-providers'],queryFn:async()=>((await api.get('/payments/providers')).data.data??[])});const memberList=computed<Membership[]>(()=>memberships.data.value??[]);const paymentList=computed<Payment[]>(()=>payments.data.value??[]);const providerOptions=computed<Provider[]>(()=>((providers.data.value??[])as Provider[]).filter(item=>item.configured));const money=(v:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(v));async function refresh(){await client.invalidateQueries({queryKey:['payments']})}function reset(){message.value='';error.value=''}
async function intent(){reset();if(!membershipId.value){error.value='Select a membership.';return}const selected=providerOptions.value.some(item=>item.name===provider.value)?provider.value:providerOptions.value[0]?.name;if(!selected){error.value='No payment provider is configured for this environment.';return}provider.value=selected;busy.value=true;try{const response=await api.post('/payments/intents',{membership_id:membershipId.value,method:method.value,provider:selected});if(selected==='xendit'){const paymentId=response.data?.data?.payment?.id;if(!paymentId)throw Error('The simulated payment could not be prepared.');await api.post(`/payments/mock/xendit/${paymentId}/complete`);message.value='Simulated Xendit payment received — membership active.';await refresh();return}const checkoutUrl=response.data?.data?.checkout_url;if(typeof checkoutUrl!=='string'){message.value='Checkout is still being prepared. Refresh payment status before trying again.';await refresh();return}const url=new URL(checkoutUrl);if(url.protocol!=='https:'||url.hostname!=='checkout.paymongo.com')throw Error('The payment provider returned an invalid checkout URL.');window.location.assign(url.toString())}catch(e:any){error.value=e.response?.data?.message??e.message??'Payment checkout could not be created.'}finally{busy.value=false}}
async function refund(p:Payment){reset();if(!refundAmount.value){error.value='Enter a refund amount.';return}busy.value=true;try{await api.post(`/payments/${p.id}/refunds`,{amount:refundAmount.value});message.value='Refund request created.'}catch(e:any){error.value=e.response?.data?.message??'Refund request could not be created.'}finally{busy.value=false}}
</script>
<template>
  <header class="page-header"><div><p class="eyebrow">BILLING</p><h1>Payments</h1><p class="muted">Start checkout and review recorded payments.</p></div></header>
  <p v-if="message" class="action-message success">{{message}}</p><p v-if="error" class="action-message error">{{error}}</p>
  <section class="panel membership-form payment-form"><h2>Pay for a membership</h2><form @submit.prevent="intent"><div class="form-grid"><label>Membership<select v-model.number="membershipId"><option :value="undefined">Select membership</option><option v-for="membership in memberList" :key="membership.id" :value="membership.id">Membership #{{membership.id}} · {{membership.status}}</option></select></label><label>Provider<select v-model="provider"><option v-for="item in providerOptions" :key="item.name" :value="item.name">{{item.mock?'Xendit (simulated)':'PayMongo'}}</option></select></label><label>Method<select v-model="method"><option>gcash</option><option>maya</option><option>card</option></select></label></div><p class="muted">The server calculates the checkout amount from the selected membership plan. Simulated Xendit checkout completes in this app.</p><button class="primary-button" :disabled="busy||!providerOptions.length">{{provider==='xendit'?'Complete simulated payment':'Continue to secure checkout'}}</button></form></section>
  <section class="panel memberships-table"><h2>Payments</h2><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Amount</th><th>Method</th><th>Provider</th><th>Status</th><th>Refund</th></tr></thead><tbody><tr v-if="!paymentList.length"><td colspan="6" class="table-empty">No payments recorded.</td></tr><tr v-for="payment in paymentList" :key="payment.id"><td>{{payment.reference}}</td><td>{{money(payment.amount)}}</td><td>{{payment.method}}</td><td>{{payment.provider||'—'}}</td><td><span :class="['status-pill',payment.status]">{{payment.status}}</span></td><td><div class="row-actions"><input v-model.number="refundAmount" class="refund-input" min="1" type="number" placeholder="Amount"/><button class="table-button cancel" :disabled="busy" @click="refund(payment)">Refund</button></div></td></tr></tbody></table></div></section>
  <PaymentOperationsView />
</template>
