<script setup lang="ts">
import { ref } from 'vue'; import { useQuery,useQueryClient } from '@tanstack/vue-query'; import { api } from '@/api/client'; import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const client=useQueryClient();const name=ref(auth.user?.name??'');const email=ref(auth.user?.email??'');const currentPassword=ref('');const password=ref('');const confirmation=ref('');const twoFactorCode=ref('');const setup=ref<{secret:string;provisioning_uri:string}|null>(null);const message=ref('');const error=ref('');const busy=ref(false)
const sessions=useQuery({queryKey:['sessions'],queryFn:async()=>((await api.get('/auth/sessions')).data.data??[])});function reset(){message.value='';error.value=''}
async function profile(){reset();busy.value=true;try{await api.patch('/profile',{name:name.value,email:email.value});await auth.hydrate();message.value='Profile updated.'}catch(e:any){error.value=e.response?.data?.message??'Profile could not be updated.'}finally{busy.value=false}}
async function changePassword(){reset();if(password.value!==confirmation.value||password.value.length<12){error.value='Use matching passwords of at least 12 characters.';return}busy.value=true;try{await api.post('/auth/change-password',{current_password:currentPassword.value,password:password.value,password_confirmation:confirmation.value});currentPassword.value='';password.value='';confirmation.value='';message.value='Password changed. Other sessions were revoked.';await client.invalidateQueries({queryKey:['sessions']})}catch(e:any){error.value=e.response?.data?.message??'Password could not be changed.'}finally{busy.value=false}}
async function startTwoFactor(){reset();busy.value=true;try{setup.value=(await api.post('/auth/two-factor/setup')).data.data;message.value='Scan the provisioning URI with your authenticator, then confirm the code.'}catch(e:any){error.value=e.response?.data?.message??'Two-factor setup could not start.'}finally{busy.value=false}}
async function confirmTwoFactor(){reset();busy.value=true;try{await api.post('/auth/two-factor/confirm',{code:twoFactorCode.value});setup.value=null;twoFactorCode.value='';message.value='Two-factor authentication enabled.'}catch(e:any){error.value=e.response?.data?.message??'Invalid authenticator code.'}finally{busy.value=false}}
async function revoke(id:number){reset();busy.value=true;try{await api.delete(`/auth/sessions/${id}`);message.value='Session revoked.';await client.invalidateQueries({queryKey:['sessions']})}catch(e:any){error.value=e.response?.data?.message??'Session could not be revoked.'}finally{busy.value=false}}
async function resendVerification(){reset();busy.value=true;try{const r=await api.post('/auth/email/verification-notification');message.value=r.data.message??'Verification link sent.'}catch(e:any){error.value=e.response?.data?.message??'Could not send verification link.'}finally{busy.value=false}}
async function disableTwoFactor(){reset();busy.value=true;try{await api.post('/auth/two-factor/disable',{code:twoFactorCode.value});twoFactorCode.value='';message.value='Two-factor authentication disabled.'}catch(e:any){error.value=e.response?.data?.message??'Could not disable two-factor authentication.'}finally{busy.value=false}}
</script>
<template><header class="page-header"><div><p class="eyebrow">ACCOUNT</p><h1>Settings</h1><p class="muted">Manage your profile, password, security, and device sessions.</p></div></header><p v-if="message" class="action-message success">{{message}}</p><p v-if="error" class="action-message error">{{error}}</p><section class="settings-grid"><article class="panel membership-form"><h2>Profile</h2><form @submit.prevent="profile"><label>Name<input v-model="name"/></label><label>Email<input v-model="email" type="email"/></label><button class="secondary-button" :disabled="busy">Save profile</button><button class="table-button" type="button" :disabled="busy" @click="resendVerification">Resend verification email</button></form></article><article class="panel membership-form"><h2>Change password</h2><form @submit.prevent="changePassword"><label>Current password<input v-model="currentPassword" type="password"/></label><label>New password<input v-model="password" type="password"/></label><label>Confirm new password<input v-model="confirmation" type="password"/></label><button class="secondary-button" :disabled="busy">Change password</button></form></article><article class="panel membership-form"><h2>Two-factor authentication</h2><p class="muted">Use an authenticator app to protect your account.</p><button v-if="!setup" class="secondary-button" :disabled="busy" @click="startTwoFactor">Set up authenticator</button><div class="two-factor" v-if="setup"><p>Secret: <code>{{setup.secret}}</code></p><p class="muted">Open this URI in an authenticator: <small>{{setup.provisioning_uri}}</small></p><input v-model="twoFactorCode" placeholder="6-digit code"/><button class="primary-button" :disabled="busy" @click="confirmTwoFactor">Confirm</button></div><div class="two-factor"><input v-model="twoFactorCode" placeholder="Authenticator code to disable"/><button class="table-button cancel" :disabled="busy" @click="disableTwoFactor">Disable 2FA</button></div></article></section><section class="panel memberships-table"><h2>Device sessions</h2><div class="table-wrap"><table><thead><tr><th>Device</th><th>Created</th><th>Last used</th><th>Action</th></tr></thead><tbody><tr v-if="!sessions.data.value?.length"><td colspan="4" class="table-empty">No sessions found.</td></tr><tr v-for="session in sessions.data.value" :key="session.id"><td>{{session.name}}</td><td>{{session.created_at}}</td><td>{{session.last_used_at||'Current / never used'}}</td><td><button class="table-button cancel" :disabled="busy" @click="revoke(session.id)">Revoke</button></td></tr></tbody></table></div></section></template>
