<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { api } from '@/api/client'
type Tournament = { id: number; name: string }
const props = defineProps<{ tournaments: Tournament[] }>(); const client = useQueryClient(); const tournamentId = ref<number>(); const teamName = ref(''); const playerId = ref<number>(); const teamId = ref<number>(); const message = ref(''); const error = ref('')
const teams = useQuery({ queryKey: computed(() => ['teams', tournamentId.value]), enabled: computed(() => !!tournamentId.value), queryFn: async () => (await api.get(`/tournaments/${tournamentId.value}/teams`)).data.data ?? [] })
const registrations = useQuery({ queryKey: computed(() => ['team-registrations', tournamentId.value]), enabled: computed(() => !!tournamentId.value), queryFn: async () => { const body = (await api.get(`/tournaments/${tournamentId.value}/registrations`)).data.data ?? []; return body.data ?? body } })
async function refresh() { await Promise.all([client.invalidateQueries({ queryKey: ['teams', tournamentId.value] }), client.invalidateQueries({ queryKey: ['team-registrations', tournamentId.value] })]) }
async function createTeam() { if (!tournamentId.value || !teamName.value.trim()) { error.value = 'Choose a tournament and enter a team name.'; return }; try { const body = await api.post(`/tournaments/${tournamentId.value}/teams`, { name: teamName.value.trim() }); teamId.value = body.data.data.id; teamName.value = ''; message.value = 'Team created.'; await refresh() } catch (caught: any) { error.value = caught.response?.data?.message ?? 'Unable to create team.' } }
async function addMember() { if (!tournamentId.value || !teamId.value || !playerId.value) { error.value = 'Choose a team and registered player.'; return }; try { await api.post(`/tournaments/${tournamentId.value}/teams/${teamId.value}/members`, { user_id: playerId.value }); message.value = 'Player added to team.'; await refresh() } catch (caught: any) { error.value = caught.response?.data?.message ?? 'Unable to add player.' } }
async function checkIn(registration: any) { try { await api.post(`/tournaments/${tournamentId.value}/registrations/${registration.id}/check-in`); message.value = 'Player checked in.'; await refresh() } catch (caught: any) { error.value = caught.response?.data?.message ?? 'Unable to check in player.' } }
</script>
<template><section class="panel membership-form payment-form"><h2>Teams &amp; event check-in</h2><div class="form-grid"><label>Tournament<select v-model.number="tournamentId" @change="teamId=undefined;playerId=undefined"><option :value="undefined">Select tournament</option><option v-for="tournament in props.tournaments" :key="tournament.id" :value="tournament.id">{{tournament.name}}</option></select></label><label>New team<input v-model="teamName" placeholder="Team name"/><button class="secondary-button" type="button" @click="createTeam">Create team</button></label></div><div v-if="tournamentId" class="form-grid team-controls"><label>Team<select v-model.number="teamId"><option :value="undefined">Select team</option><option v-for="team in teams.data.value??[]" :key="team.id" :value="team.id">{{team.name}}</option></select></label><label>Registered player<select v-model.number="playerId"><option :value="undefined">Select player</option><option v-for="registration in registrations.data.value??[]" :key="registration.id" :value="registration.user_id">{{registration.user?.name??`Player #${registration.user_id}`}}</option></select></label></div><button v-if="tournamentId" class="secondary-button" type="button" @click="addMember">Add player to team</button><p v-if="message" class="action-message success">{{message}}</p><p v-if="error" class="action-message error">{{error}}</p><div v-if="tournamentId" class="checkin-list"><div v-for="registration in registrations.data.value??[]" :key="registration.id"><span>{{registration.user?.name??`Player #${registration.user_id}`}} · {{registration.checked_in_at?'Checked in':'Awaiting check-in'}}</span><button v-if="!registration.checked_in_at && registration.status!=='cancelled'" class="table-button confirm" @click="checkIn(registration)">Check in</button></div></div></section></template>
