<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { api } from '@/api/client'
import TournamentMatchesView from '@/views/TournamentMatchesView.vue'
type Tournament={id:number;name:string;format:string;starts_at:string;entry_fee?:number};const client=useQueryClient();const name=ref('');const facilityId=ref<number>();const branchId=ref<number>();const format=ref('singles');const starts=ref('');const fee=ref<number>();const msg=ref('');const err=ref('');const busy=ref(false)
const facilities=useQuery({queryKey:['facilities'],queryFn:async()=>((await api.get('/facilities')).data.data??[])});const branches=useQuery({queryKey:computed(()=>['tournament-branches',facilityId.value]),enabled:computed(()=>!!facilityId.value),queryFn:async()=>((await api.get(`/facilities/${facilityId.value}/branches`)).data.data??[])});const tournaments=useQuery({queryKey:['tournaments'],queryFn:async()=>{const r=await api.get('/tournaments');return r.data.data??[]}});const list=computed<Tournament[]>(()=>tournaments.data.value??[])
async function create(){if(!name.value||!branchId.value||!starts.value){err.value='Enter a name, select a branch, and choose a start date.';return}busy.value=true;try{await api.post('/tournaments',{name:name.value,branch_id:branchId.value,format:format.value,starts_at:starts.value,entry_fee:fee.value});msg.value='Tournament created.';name.value='';await client.invalidateQueries({queryKey:['tournaments']})}catch(e:any){err.value=e.response?.data?.message??'Tournament could not be created.'}finally{busy.value=false}}async function register(t:Tournament){try{await api.post(`/tournaments/${t.id}/registrations`);msg.value='Registered for tournament.'}catch(e:any){err.value=e.response?.data?.message??'Registration failed.'}}</script>
<template><header class="page-header"><div><p class="eyebrow">EVENTS</p><h1>Tournaments</h1><p class="muted">Create events, register players, and manage results.</p></div></header><p v-if="msg" class="action-message success">{{msg}}</p><p v-if="err" class="action-message error">{{err}}</p><section class="panel membership-form payment-form"><h2>Create tournament</h2><form @submit.prevent="create"><div class="form-grid"><label>Name<input v-model="name"/></label><label>Facility<select v-model.number="facilityId" @change="branchId=undefined"><option :value="undefined">Select facility</option><option v-for="facility in facilities.data.value??[]" :key="facility.id" :value="facility.id">{{facility.name}}</option></select></label><label>Branch<select v-model.number="branchId" :disabled="!facilityId"><option :value="undefined">Select branch</option><option v-for="branch in branches.data.value??[]" :key="branch.id" :value="branch.id">{{branch.name}}</option></select></label><label>Format<select v-model="format"><option>singles</option><option>doubles</option><option>team</option></select></label><label>Starts at<input v-model="starts" type="datetime-local"/></label><label>Entry fee<input v-model.number="fee" type="number" min="0"/></label></div><button class="primary-button" :disabled="busy">Create tournament</button></form></section><section class="plan-grid"><article v-for="tournament in list" :key="tournament.id" class="panel plan-card"><span class="status-pill confirmed">{{tournament.format}}</span><h2>{{tournament.name}}</h2><p>{{tournament.starts_at}}</p><p>Entry: ₱{{tournament.entry_fee??0}}</p><button class="secondary-button" @click="register(tournament)">Register me</button></article></section><TournamentMatchesView :tournaments="list" /></template>
